runtime: python39
entrypoint: gunicorn -b :$PORT app:app --workers=${WEB_CONCURRENCY} --threads=${THREADS} --timeout=${TIMEOUT} --worker-class=${WORKER_CLASS}

instance_class: F2
automatic_scaling:
  min_idle_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

env_variables:
  WEB_CONCURRENCY: 1
  TIMEOUT: 120
  WORKER_CLASS: gthread
  THREADS: 5

  # 🔽 修改為新的測試資料庫連線資訊
  DB_HOST: /cloudsql/rolence-project:asia-east2:vf-life-uat-db
  DB_PORT: 5432
  DB_USER: postgres
  DB_NAME: postgres
  DB_PASSWORD: "Test123456!"

service: default

# 🔽 對應新 Cloud SQL instance 的 socket 掛載設定
beta_settings:
  cloud_sql_instances: rolence-project:asia-east2:vf-life-uat-db
